// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZPkbf5fSutFYQp0hIBxHbizIJRxQ7oWY',
    appId: '1:486083373949:web:3071e4b41901977f40fa14',
    messagingSenderId: '486083373949',
    projectId: 'alice-f14af',
    authDomain: 'alice-f14af.firebaseapp.com',
    storageBucket: 'alice-f14af.firebasestorage.app',
    measurementId: 'G-GPBSNP2R99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChQPpBs9TGDv5sdIoAELb4bb2Xs57QorU',
    appId: '1:486083373949:android:36989bf33ea8addc40fa14',
    messagingSenderId: '486083373949',
    projectId: 'alice-f14af',
    storageBucket: 'alice-f14af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDVdNnTOFQtU5dNIkVRC9GryFIm-FkkfY',
    appId: '1:486083373949:ios:7337b95f89357c8740fa14',
    messagingSenderId: '486083373949',
    projectId: 'alice-f14af',
    storageBucket: 'alice-f14af.firebasestorage.app',
    iosBundleId: 'com.alice.aliceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDVdNnTOFQtU5dNIkVRC9GryFIm-FkkfY',
    appId: '1:486083373949:ios:30be0541ddfe57ba40fa14',
    messagingSenderId: '486083373949',
    projectId: 'alice-f14af',
    storageBucket: 'alice-f14af.firebasestorage.app',
    iosBundleId: 'com.example.aliceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZPkbf5fSutFYQp0hIBxHbizIJRxQ7oWY',
    appId: '1:486083373949:web:9993836fc2a72a0940fa14',
    messagingSenderId: '486083373949',
    projectId: 'alice-f14af',
    authDomain: 'alice-f14af.firebaseapp.com',
    storageBucket: 'alice-f14af.firebasestorage.app',
    measurementId: 'G-FCSP9KC8Q7',
  );

}