use_frameworks!
use_modular_headers!

target 'Runner' do
  platform :ios, '12.0'

  # ✅ ADD THIS LINE FOR FIREBASE
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
